### ISSUE TITLE
Broken inspection for QueryTrait::orderBy()

### ISSUE THREAD

**Issue by chriscpty** [insperedia/yiidea-support#22]
When writing a query and calling orderBy() with fields from the query (e.g. `(new \yii\db\Query())->orderBy(['my_id' => SORT_ASC])`), an inspection error is thrown saying that `Field 'my_id' not exists in referenced class \yii\db\ExpressionInterface`.

This seems to be a false positive from yii2's ability to pass arrays rather than their corresponding options - yiidea-support seems to think that this array is supposed to be instantiated as a `\yii\db\Expression` because that's another possible argument to `orderBy`.

A possible fix could be to have that inspection be more context sensitive rather than always assuming that, if you can pass an array or a specific class, the array must always have that class's shape.

**Comment by verifiera** [comment]
Thank you for the issue. I will take a look.

**Comment by insperedia** [comment]
Thank you for the issue. I will take a look.

**Comment by insperedia** [comment]
Yii framework has this case when the array is passed as a param without class shape.
However, I disabled this behavior for the ExpressionInterface parameter type, which should solve your problem.
We will publish a new version in a few days.

**Comment by chriscpty** [comment]
@insperedia seeing as it's been a month without a release, do you have a rough idea of when you'll publish the next version? :)

**Comment by verifiera** [comment]
I am working on a feature that disables the plugin for non-Yii projects. Unfortunately, it did not go well so that it will require 1-3 weeks. 
regarding this issue, I made this particular change; I just wanted to make a release with a more significant update. Of course, if you have troubles with this particular change, I think I can upload a new version this week or upload it in beta channel.
